### ISSUE TITLE
Set icon color

### ISSUE THREAD

**Issue by costa-alex** [patrickfnielsen/hass-room-card#1]
Hi,

Not an issue but an enhancement request. It would be nice to be able to set a color for the main icon as well as the entities icons. Templating would be great 👍

**Comment by patrickfnielsen** [comment]
Hi,
Good feedback, I'll see what I can do

**Comment by patrickfnielsen** [comment]
FYI: I hope to have this added in version 2.0 that will be released later this week.

**Comment by patrickfnielsen** [comment]
Version 2.0 have been released with this: https://github.com/patrickfnielsen/hass-room-card/releases/tag/v2.0.0
There's some breaking changes, but there's also an editor now to make it easier to use.

Let me know if there's any issues :)
